#define request
Header      header
string      sender
string      receiver
uint32      trans_id
string      cmd
string      data
---
#define response
uint32      trans_id
string      ack
string      data
